CreateUsersTable: create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `telefone` varchar(191) not null, `email` varchar(191) not null, `email_verified_at` timestamp null, `password` varchar(191) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(191) not null, `token` varchar(191) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CreateCupomDescontosTable: create table `cupom_descontos` (`id` int unsigned not null auto_increment primary key, `nome` varchar(191) not null, `localizador` varchar(191) not null, `desconto` decimal(6, 2) not null default '0', `modo_desconto` enum('valor', 'porc') not null default 'porc', `limite` decimal(6, 2) not null default '0', `modo_limite` enum('valor', 'qtd') not null default 'qtd', `dthr_validade` datetime not null, `ativo` enum('S', 'N') not null default 'S', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateCupomDescontosTable: alter table `cupom_descontos` add unique `cupom_descontos_localizador_unique`(`localizador`)
CreateEnderecosTable: create table `enderecos` (`rua` varchar(191) not null, `cidade` varchar(191) not null, `bairro` varchar(191) not null, `numero` int not null, `complemento` varchar(191) null, `uf` varchar(191) not null, `cep` varchar(191) not null, `user_id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateEnderecosTable: alter table `enderecos` add constraint `enderecos_user_id_foreign` foreign key (`user_id`) references `users` (`id`)
CreateCategoriasTable: create table `categorias` (`id` int unsigned not null auto_increment primary key, `nome` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateProdutosTable: create table `produtos` (`id` int unsigned not null auto_increment primary key, `nome_produto` varchar(191) not null, `tipo` varchar(191) not null, `codtipo` varchar(191) not null, `marca` varchar(191) not null, `valor` decimal(6, 2) not null, `descricao` text not null, `imagem` varchar(191) not null, `caracteristica` text not null, `peso` varchar(191) null, `altura` varchar(191) null, `largura` varchar(191) null, `comprimento` varchar(191) null, `diametro` varchar(191) null, `ativo` enum('S', 'N') not null default 'S', `categoria_id` int unsigned not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateProdutosTable: alter table `produtos` add constraint `produtos_categoria_id_foreign` foreign key (`categoria_id`) references `categorias` (`id`)
CreatePedidosTable: create table `pedidos` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned not null, `status` enum('RE', 'PA', 'CA', 'PE') not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePedidosTable: alter table `pedidos` add constraint `pedidos_user_id_foreign` foreign key (`user_id`) references `users` (`id`)
CreatePedidoProdutosTable: create table `pedido_produtos` (`id` int unsigned not null auto_increment primary key, `pedido_id` int unsigned not null, `produto_id` int unsigned not null, `status` enum('RE', 'PA', 'CA', 'PE') not null, `valor` int not null default '0', `desconto` decimal(6, 2) not null default '0', `cupom_desconto_id` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePedidoProdutosTable: alter table `pedido_produtos` add constraint `pedido_produtos_pedido_id_foreign` foreign key (`pedido_id`) references `pedidos` (`id`)
CreatePedidoProdutosTable: alter table `pedido_produtos` add constraint `pedido_produtos_produto_id_foreign` foreign key (`produto_id`) references `produtos` (`id`)
CreatePedidoProdutosTable: alter table `pedido_produtos` add constraint `pedido_produtos_cupom_desconto_id_foreign` foreign key (`cupom_desconto_id`) references `cupom_descontos` (`id`)
UpdateTableCategorias: alter table `categorias` add `deleted_at` timestamp null
CreateUserfisTable: create table `userfis` (`cpf` varchar(191) not null, `user_id` int unsigned not null, `id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUserfisTable: alter table `userfis` add constraint `userfis_user_id_foreign` foreign key (`user_id`) references `users` (`id`)
CreateUserfisTable: alter table `userfis` add unique `userfis_cpf_unique`(`cpf`)
CreateUserjursTable: create table `userjurs` (`id` int unsigned not null auto_increment primary key, `rsocial` varchar(191) not null, `cnpj` varchar(191) not null, `user_id` int unsigned not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUserjursTable: alter table `userjurs` add constraint `userjurs_user_id_foreign` foreign key (`user_id`) references `users` (`id`)
CreateUserjursTable: alter table `userjurs` add unique `userjurs_rsocial_unique`(`rsocial`)
CreateUserjursTable: alter table `userjurs` add unique `userjurs_cnpj_unique`(`cnpj`)
CreateAdminsTable: create table `admins` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `email` varchar(191) not null, `password` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateAdminsTable: alter table `admins` add unique `admins_email_unique`(`email`)
